<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="7" passed="6" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-05-06T22:22:52 EDT" name="Default suite" finished-at="2024-05-06T22:22:57 EDT" duration-ms="4618">
    <groups>
    </groups>
    <test started-at="2024-05-06T22:22:52 EDT" name="Default test" finished-at="2024-05-06T22:22:57 EDT" duration-ms="4618">
      <class name="com.sandeepkaur.University.UniversityApiTests">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.sandeepkaur.University.UniversityApiTests@2b91004a]" started-at="2024-05-06T22:22:52 EDT" name="setUp" finished-at="2024-05-06T22:22:53 EDT" duration-ms="1173" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="create()[pri:0, instance:com.sandeepkaur.University.UniversityApiTests@2b91004a]" started-at="2024-05-06T22:22:53 EDT" name="create" finished-at="2024-05-06T22:22:56 EDT" duration-ms="2663" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create -->
        <test-method signature="testHappyPath()[pri:0, instance:com.sandeepkaur.University.UniversityApiTests@2b91004a]" started-at="2024-05-06T22:22:56 EDT" name="testHappyPath" finished-at="2024-05-06T22:22:56 EDT" duration-ms="175" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testHappyPath -->
        <test-method signature="testInvalidRequests()[pri:0, instance:com.sandeepkaur.University.UniversityApiTests@2b91004a]" started-at="2024-05-06T22:22:56 EDT" name="testInvalidRequests" finished-at="2024-05-06T22:22:56 EDT" duration-ms="110" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[1 expectation failed.
Expected status code <422> but was <201>.
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <422> but was <201>.

at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:73)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:108)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:512)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:696)
at io.restassured.internal.ResponseSpecificationImpl.this$2$validateResponseIfRequired(ResponseSpecificationImpl.groovy)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:198)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:62)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:135)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:143)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at com.sandeepkaur.University.UniversityApiTests.testInvalidRequests(UniversityApiTests.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidRequests -->
        <test-method signature="testMissingAuth()[pri:0, instance:com.sandeepkaur.University.UniversityApiTests@2b91004a]" started-at="2024-05-06T22:22:56 EDT" name="testMissingAuth" finished-at="2024-05-06T22:22:57 EDT" duration-ms="137" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testMissingAuth -->
        <test-method signature="testUnauthorizedAccess()[pri:0, instance:com.sandeepkaur.University.UniversityApiTests@2b91004a]" started-at="2024-05-06T22:22:57 EDT" name="testUnauthorizedAccess" finished-at="2024-05-06T22:22:57 EDT" duration-ms="51" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUnauthorizedAccess -->
        <test-method signature="testUnencodedParameter()[pri:0, instance:com.sandeepkaur.University.UniversityApiTests@2b91004a]" started-at="2024-05-06T22:22:57 EDT" name="testUnencodedParameter" finished-at="2024-05-06T22:22:57 EDT" duration-ms="154" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUnencodedParameter -->
        <test-method signature="testUrlPathError()[pri:0, instance:com.sandeepkaur.University.UniversityApiTests@2b91004a]" started-at="2024-05-06T22:22:57 EDT" name="testUrlPathError" finished-at="2024-05-06T22:22:57 EDT" duration-ms="51" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUrlPathError -->
      </class> <!-- com.sandeepkaur.University.UniversityApiTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
